In [95]:
import numpy as np

samples = 1000
dimension = 4

beta = np.random.randn(dimension)

def S(beta, gamma):
    if gamma >= beta:
        return 0
    else:
        return beta - gamma if beta > 0 else beta + gamma

gamma = 0.5
y_tilde = np.zeros((dimension,))
X = np.random.randn(samples, dimension)
y = np.random.randn(samples, 1)
y = (X[:, 0] + X[:, 2] + X[:, 3]).reshape(samples, 1)
y -= np.mean(y)
y /= np.std(y)

for _ in range(50):
    for j in range(dimension):
        # Calculate y_tilde
        y_tilde = np.zeros((samples,))
        for i in range(samples):
            for k in range(dimension):
                y_tilde[i] = X[i, k] * beta[k]
        f1 = beta[j]
        for i in range(samples):
            f1 += X[i, j] * (y[i] - y_tilde[i])
        beta[j] = S(f1 / samples, gamma)
    print(beta)

[ 0.06629161  0.          0.09867136  0.        ]
[ 0.06040988  0.          0.07167674  0.05233648]
[ 0.06073785  0.          0.07308027  0.0019389 ]
[ 0.06041669  0.          0.07170414  0.05046941]
[ 0.06072594  0.          0.07302926  0.0037368 ]
[ 0.06042815  0.          0.07175324  0.04873812]
[ 0.06071491  0.          0.07298199  0.00540395]
[ 0.06043877  0.          0.07179876  0.04713273]
[ 0.06070468  0.          0.07293815  0.00694987]
[ 0.06044862  0.          0.07184097  0.04564408]
[ 0.0606952   0.          0.07289751  0.00838337]
[ 0.06045776  0.          0.07188011  0.04426369]
[ 0.0606864   0.          0.07285982  0.00971262]
[ 0.06046623  0.          0.0719164   0.04298369]
[ 0.06067824  0.          0.07282487  0.0109452 ]
[ 0.06047408  0.          0.07195006  0.04179676]
[ 0.06067068  0.          0.07279246  0.01208815]
[ 0.06048137  0.          0.07198127  0.04069616]
[ 0.06066367  0.          0.0727624   0.01314799]
[ 0.06048812  0.          0.07201021  0.03967558]
